### ISSUE TITLE
MacOS X: Installation/Build failure

### ISSUE THREAD

**Issue by jxsl13** [iti-luebeck/RTeasy2#31]
When trying to install it:
```
[2017-12-14 20:03:52.021]:     An unexpected exception happened in thread main
[2017-12-14 20:03:52.021]:     java.lang.NoSuchMethodError: com.apple.eawt.Application.removeAboutMenuItem()V
[2017-12-14 20:03:52.021]:     	at org.netbeans.installer.wizard.containers.SwingFrameContainer.initializeMacOS(SwingFrameContainer.java:446)
[2017-12-14 20:03:52.022]:     	at org.netbeans.installer.wizard.containers.SwingFrameContainer.initComponents(SwingFrameContainer.java:374)
[2017-12-14 20:03:52.022]:     	at org.netbeans.installer.wizard.containers.SwingFrameContainer.<init>(SwingFrameContainer.java:184)
[2017-12-14 20:03:52.022]:     	at org.netbeans.installer.wizard.Wizard.newWizardContainer(Wizard.java:499)
[2017-12-14 20:03:52.022]:     	at org.netbeans.installer.wizard.Wizard.open(Wizard.java:529)
[2017-12-14 20:03:52.022]:     	at org.netbeans.installer.Installer.start(Installer.java:144)
[2017-12-14 20:03:52.022]:     	at org.netbeans.installer.Installer.main(Installer.java:81)
[2017-12-14 20:03:52.023]:     ... show message dialog
[2017-12-14 20:03:52.023]:         title: Critical Error
[2017-12-14 20:03:52.023]:         message: An unexpected exception happened in thread main
[2017-12-14 20:03:52.023]:
[2017-12-14 20:03:52.023]:         Exception:
[2017-12-14 20:03:52.023]:           java.lang.NoSuchMethodError:
[2017-12-14 20:03:52.023]:           com.apple.eawt.Application.removeAboutMenuItem()V
[2017-12-14 20:03:52.024]:
[2017-12-14 20:03:52.024]:         You can get more details about the issue in the installer log file:
[2017-12-14 20:03:52.024]:          /Users/john/.application-installer/log/20171214200351.log

```

Log file content:
```
[2017-12-14 20:03:51.168]: entering -- org.netbeans.installer.Installer.main():81
[2017-12-14 20:03:51.170]: initializing the installer engine
[2017-12-14 20:03:51.170]:     entering -- org.netbeans.installer.Installer.<init>():116
[2017-12-14 20:03:51.170]:     ... initializing ErrorHandler
[2017-12-14 20:03:51.172]:     ... end of ErrorHandler initialization
[2017-12-14 20:03:51.172]:     exiting -- org.netbeans.installer.Installer.<init>():116
[2017-12-14 20:03:51.172]:     entering -- org.netbeans.installer.Installer.<init>():117
[2017-12-14 20:03:51.172]:     dumping target system information
[2017-12-14 20:03:51.172]:         system properties:
[2017-12-14 20:03:51.175]:             awt.toolkit => sun.lwawt.macosx.LWCToolkit
[2017-12-14 20:03:51.175]:             file.encoding => UTF-8
[2017-12-14 20:03:51.175]:             file.encoding.pkg => sun.io
[2017-12-14 20:03:51.175]:             file.separator => /
[2017-12-14 20:03:51.175]:             ftp.nonProxyHosts => local|*.local|169.254/16|*.169.254/16
[2017-12-14 20:03:51.175]:             gopherProxySet => false
[2017-12-14 20:03:51.175]:             http.nonProxyHosts => local|*.local|169.254/16|*.169.254/16
[2017-12-14 20:03:51.175]:             java.awt.graphicsenv => sun.awt.CGraphicsEnvironment
[2017-12-14 20:03:51.175]:             java.awt.printerjob => sun.lwawt.macosx.CPrinterJob
[2017-12-14 20:03:51.176]:             java.class.path => /Users/john/Desktop/RTeasy Installer 2.app/Contents/Resources/RTeasy Installer/bundle.jar
[2017-12-14 20:03:51.176]:             java.class.version => 53.0
[2017-12-14 20:03:51.176]:             java.home => /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
[2017-12-14 20:03:51.176]:             java.io.tmpdir => /var/folders/1g/ntlc7xt92d59z_mkzycjxvq80000gn/T/
[2017-12-14 20:03:51.176]:             java.library.path => /Users/john/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
[2017-12-14 20:03:51.176]:             java.runtime.name => Java(TM) SE Runtime Environment
[2017-12-14 20:03:51.176]:             java.runtime.version => 9.0.1+11
[2017-12-14 20:03:51.176]:             java.specification.name => Java Platform API Specification
[2017-12-14 20:03:51.176]:             java.specification.vendor => Oracle Corporation
[2017-12-14 20:03:51.176]:             java.specification.version => 9
[2017-12-14 20:03:51.176]:             java.vendor => Oracle Corporation
[2017-12-14 20:03:51.176]:             java.vendor.url => http://java.oracle.com/
[2017-12-14 20:03:51.176]:             java.vendor.url.bug => http://bugreport.java.com/bugreport/
[2017-12-14 20:03:51.176]:             java.version => 9.0.1
[2017-12-14 20:03:51.177]:             java.vm.compressedOopsMode => Zero based
[2017-12-14 20:03:51.177]:             java.vm.info => mixed mode
[2017-12-14 20:03:51.177]:             java.vm.name => Java HotSpot(TM) 64-Bit Server VM
[2017-12-14 20:03:51.177]:             java.vm.specification.name => Java Virtual Machine Specification
[2017-12-14 20:03:51.177]:             java.vm.specification.vendor => Oracle Corporation
[2017-12-14 20:03:51.177]:             java.vm.specification.version => 9
[2017-12-14 20:03:51.177]:             java.vm.vendor => Oracle Corporation
[2017-12-14 20:03:51.177]:             java.vm.version => 9.0.1+11
[2017-12-14 20:03:51.177]:             jdk.debug => release
[2017-12-14 20:03:51.177]:             line.separator => 
[2017-12-14 20:03:51.177]:             os.arch => x86_64
[2017-12-14 20:03:51.177]:             os.name => Mac OS X
[2017-12-14 20:03:51.177]:             os.version => 10.13.2
[2017-12-14 20:03:51.177]:             path.separator => :
[2017-12-14 20:03:51.178]:             socksNonProxyHosts => local|*.local|169.254/16|*.169.254/16
[2017-12-14 20:03:51.178]:             sun.arch.data.model => 64
[2017-12-14 20:03:51.178]:             sun.boot.library.path => /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/lib
[2017-12-14 20:03:51.178]:             sun.cpu.endian => little
[2017-12-14 20:03:51.178]:             sun.cpu.isalist => 
[2017-12-14 20:03:51.178]:             sun.io.unicode.encoding => UnicodeBig
[2017-12-14 20:03:51.178]:             sun.java.command => /Users/john/Desktop/RTeasy Installer 2.app/Contents/Resources/RTeasy Installer/bundle.jar
[2017-12-14 20:03:51.178]:             sun.java.launcher => SUN_STANDARD
[2017-12-14 20:03:51.178]:             sun.jnu.encoding => UTF-8
[2017-12-14 20:03:51.178]:             sun.management.compiler => HotSpot 64-Bit Tiered Compilers
[2017-12-14 20:03:51.178]:             sun.os.patch.level => unknown
[2017-12-14 20:03:51.178]:             user.country => DE
[2017-12-14 20:03:51.178]:             user.dir => /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/bin
[2017-12-14 20:03:51.178]:             user.home => /Users/john
[2017-12-14 20:03:51.178]:             user.language => de
[2017-12-14 20:03:51.178]:             user.name => john
[2017-12-14 20:03:51.179]:             user.timezone => Europe/Berlin
[2017-12-14 20:03:51.179]:     ... end of target system information
[2017-12-14 20:03:51.179]:     exiting -- org.netbeans.installer.Installer.<init>():117
[2017-12-14 20:03:51.200]:     loading jni library
[2017-12-14 20:03:51.200]:         library resource path: native/jnilib/macosx/macosx.dylib
[2017-12-14 20:03:51.245]:         library file path: /var/folders/1g/ntlc7xt92d59z_mkzycjxvq80000gn/T/nbi-13175905390005173135.tmp
[2017-12-14 20:03:51.249]:         ... successfully loaded the library
[2017-12-14 20:03:51.251]:     entering -- org.netbeans.installer.Installer.<init>():122
[2017-12-14 20:03:51.252]:     parsing command-line arguments
[2017-12-14 20:03:51.253]:         ... no command line arguments were specified
[2017-12-14 20:03:51.253]:     ... finished parsing command line arguments
[2017-12-14 20:03:51.253]:     exiting -- org.netbeans.installer.Installer.<init>():122
[2017-12-14 20:03:51.253]:     entering -- org.netbeans.installer.Installer.<init>():123
[2017-12-14 20:03:51.253]:     loading engine properties
[2017-12-14 20:03:51.253]:         loading engine properties
[2017-12-14 20:03:51.257]:             loading nbi.wizard.ui.swing.frame.width.default => 600
[2017-12-14 20:03:51.257]:             loading nbi.wizard.ui.swing.frame.width.gtk => 704
[2017-12-14 20:03:51.257]:             loading nbi.wizard.ui.swing.frame.head.left.image => resource:org/mycompany/installer/wizard/wizard-description-background-left.png
[2017-12-14 20:03:51.257]:             loading nbi.wizard.ui.swing.frame.head.right.image => resource:org/mycompany/installer/wizard/wizard-description-background-right.png
[2017-12-14 20:03:51.257]:             loading nbi.wizard.ui.swing.frame.minimum.width.nimbus => 624
[2017-12-14 20:03:51.257]:             loading nbi.wizard.ui.swing.frame.minimum.height.win.xp => 450
[2017-12-14 20:03:51.257]:             loading nbi.wizard.ui.swing.frame.minimum.height.nimbus => 512
[2017-12-14 20:03:51.257]:             loading nbi.wizard.ui.swing.frame.title.prefix => RTeasy Installer
[2017-12-14 20:03:51.257]:             loading nbi.wizard.components.instance.uri => resource:org/mycompany/installer/wizard/wizard-components.xml
[2017-12-14 20:03:51.257]:             loading nbi.wizard.ui.swing.frame.width.nimbus => 624
[2017-12-14 20:03:51.257]:             loading nbi.wizard.ui.swing.frame.width.win.xp => 600
[2017-12-14 20:03:51.257]:             loading nbi.wizard.ui.swing.frame.minimum.height.win.classic => 442
[2017-12-14 20:03:51.257]:             loading nbi.wizard.ui.swing.welcome.left.top.image => resource:org/mycompany/installer/wizard/components/panels/resources/welcome-left-top.png
[2017-12-14 20:03:51.257]:             loading nbi.wizard.ui.swing.frame.minimum.width.default => 600
[2017-12-14 20:03:51.257]:             loading nbi.wizard.ui.swing.frame.height.motif => 470
[2017-12-14 20:03:51.257]:             loading nbi.wizard.ui.swing.frame.height.aqua => 480
[2017-12-14 20:03:51.258]:             loading nbi.wizard.ui.swing.frame.minimum.width.win.xp => 600
[2017-12-14 20:03:51.258]:             loading nbi.local.directory.path => $S{user.home}/.application-installer
[2017-12-14 20:03:51.258]:             loading nbi.wizard.ui.swing.frame.minimum.height.aqua => 480
[2017-12-14 20:03:51.258]:             loading nbi.wizard.ui.swing.frame.minimum.height.default => 500
[2017-12-14 20:03:51.258]:             loading nbi.product.suggest.install => true
[2017-12-14 20:03:51.258]:             loading nbi.wizard.ui.swing.frame.icon => resource:org/mycompany/installer/wizard/wizard-icon.png
[2017-12-14 20:03:51.258]:             loading nbi.wizard.ui.swing.frame.minimum.height.gtk => 528
[2017-12-14 20:03:51.258]:             loading nbi.wizard.ui.swing.frame.width.aqua => 640
[2017-12-14 20:03:51.258]:             loading nbi.wizard.ui.swing.frame.minimum.height.motif => 470
[2017-12-14 20:03:51.258]:             loading nbi.wizard.ui.swing.frame.width.motif => 624
[2017-12-14 20:03:51.258]:             loading nbi.product.remove.corrupted.products.silently => true
[2017-12-14 20:03:51.258]:             loading nbi.wizard.ui.swing.frame.minimum.width.win.classic => 588
[2017-12-14 20:03:51.258]:             loading nbi.wizard.ui.swing.welcome.left.bottom.image => resource:org/mycompany/installer/wizard/components/panels/resources/welcome-left-bottom.png
[2017-12-14 20:03:51.258]:             loading nbi.macosx.application.directory.name => RTeasy Installer
[2017-12-14 20:03:51.258]:             loading nbi.wizard.ui.swing.frame.height.gtk => 528
[2017-12-14 20:03:51.258]:             loading nbi.wizard.ui.swing.frame.minimum.width.metal => 624
[2017-12-14 20:03:51.258]:             loading nbi.wizard.ui.swing.frame.minimum.width.motif => 624
[2017-12-14 20:03:51.258]:             loading nbi.wizard.ui.swing.frame.height.metal => 470
[2017-12-14 20:03:51.259]:             loading nbi.wizard.ui.swing.frame.minimum.width.gtk => 704
[2017-12-14 20:03:51.259]:             loading nbi.wizard.ui.swing.frame.width.metal => 624
[2017-12-14 20:03:51.259]:             loading nbi.wizard.ui.swing.frame.height.win.classic => 442
[2017-12-14 20:03:51.259]:             loading nbi.wizard.ui.swing.frame.height.win.xp => 450
[2017-12-14 20:03:51.259]:             loading nbi.wizard.ui.swing.frame.height.default => 500
[2017-12-14 20:03:51.259]:             loading nbi.wizard.ui.swing.frame.height.nimbus => 512
[2017-12-14 20:03:51.259]:             loading nbi.wizard.ui.swing.frame.width.win.classic => 588
[2017-12-14 20:03:51.259]:             loading nbi.wizard.ui.swing.frame.title.pattern => {0}
[2017-12-14 20:03:51.259]:             loading nbi.wizard.ui.swing.frame.minimum.width.aqua => 640
[2017-12-14 20:03:51.259]:             loading nbi.wizard.ui.swing.frame.minimum.height.metal => 470
[2017-12-14 20:03:51.259]:     ... finished loading engine properties
[2017-12-14 20:03:51.259]:     exiting -- org.netbeans.installer.Installer.<init>():123
[2017-12-14 20:03:51.259]:     initializing the local directory
[2017-12-14 20:03:51.259]:         ... local directory path (initial) : $S{user.home}/.application-installer
[2017-12-14 20:03:51.263]:         NameResolver - to parse $S{user.home}/.application-installer
[2017-12-14 20:03:51.272]:         ... local directory path (resolved): /Users/john/.application-installer
[2017-12-14 20:03:51.272]:         ... local directory: /Users/john/.application-installer
[2017-12-14 20:03:51.272]:     ... finished initializing local directory
[2017-12-14 20:03:51.283]:     entering -- org.netbeans.installer.Installer.<init>():129
[2017-12-14 20:03:51.283]:     ... initializing DownloadManager
[2017-12-14 20:03:51.287]:         file not exist, queue is empty!
[2017-12-14 20:03:51.293]:     ... end of initializing DownloadManager
[2017-12-14 20:03:51.293]:     exiting -- org.netbeans.installer.Installer.<init>():129
[2017-12-14 20:03:51.293]:     entering -- org.netbeans.installer.Installer.<init>():130
[2017-12-14 20:03:51.293]:     ... initializing Registry
[2017-12-14 20:03:51.302]:     ... end of initializing ErrorHandler
[2017-12-14 20:03:51.302]:     exiting -- org.netbeans.installer.Installer.<init>():130
[2017-12-14 20:03:51.302]:     entering -- org.netbeans.installer.Installer.<init>():131
[2017-12-14 20:03:51.302]:     ... initializing Wizard
[2017-12-14 20:03:51.484]:         ... loading registry from resource:data/registry.xml
[2017-12-14 20:03:51.524]:         entering -- org.netbeans.installer.product.Registry.loadProductRegistry():991
[2017-12-14 20:03:51.524]:         validating previous installations
[2017-12-14 20:03:51.524]:         ... validating installations finished
[2017-12-14 20:03:51.525]:         exiting -- org.netbeans.installer.product.Registry.loadProductRegistry():991
[2017-12-14 20:03:51.543]:     ... end of initializing Wizard
[2017-12-14 20:03:51.543]:     exiting -- org.netbeans.installer.Installer.<init>():131
[2017-12-14 20:03:51.544]:     creating lock file
[2017-12-14 20:03:51.544]:         ... created lock file: /Users/john/.application-installer/.nbilock
[2017-12-14 20:03:51.544]:     finished creating lock file
[2017-12-14 20:03:51.544]: ... finished initializing the engine
[2017-12-14 20:03:51.544]: exiting -- org.netbeans.installer.Installer.main():81
[2017-12-14 20:03:51.544]: entering -- org.netbeans.installer.Installer.main():81
[2017-12-14 20:03:51.544]: starting the installer
[2017-12-14 20:03:51.547]:     ... initializing look and feel
[2017-12-14 20:03:51.548]:         ... custom look and feel class name was not specified, using system default
[2017-12-14 20:03:51.780]:         ... class name: com.apple.laf.AquaLookAndFeel
[2017-12-14 20:03:51.780]:         ... get installed L&Fs
[2017-12-14 20:03:51.936]:         ... set specified L&F
[2017-12-14 20:03:51.938]:         ... check headless
[2017-12-14 20:03:51.939]:         ... L&F is set
[2017-12-14 20:03:51.939]:     ... initializing L&F finished
[2017-12-14 20:03:52.021]:     An unexpected exception happened in thread main
[2017-12-14 20:03:52.021]:     java.lang.NoSuchMethodError: com.apple.eawt.Application.removeAboutMenuItem()V
[2017-12-14 20:03:52.021]:     	at org.netbeans.installer.wizard.containers.SwingFrameContainer.initializeMacOS(SwingFrameContainer.java:446)
[2017-12-14 20:03:52.022]:     	at org.netbeans.installer.wizard.containers.SwingFrameContainer.initComponents(SwingFrameContainer.java:374)
[2017-12-14 20:03:52.022]:     	at org.netbeans.installer.wizard.containers.SwingFrameContainer.<init>(SwingFrameContainer.java:184)
[2017-12-14 20:03:52.022]:     	at org.netbeans.installer.wizard.Wizard.newWizardContainer(Wizard.java:499)
[2017-12-14 20:03:52.022]:     	at org.netbeans.installer.wizard.Wizard.open(Wizard.java:529)
[2017-12-14 20:03:52.022]:     	at org.netbeans.installer.Installer.start(Installer.java:144)
[2017-12-14 20:03:52.022]:     	at org.netbeans.installer.Installer.main(Installer.java:81)
[2017-12-14 20:03:52.023]:     ... show message dialog
[2017-12-14 20:03:52.023]:         title: Critical Error
[2017-12-14 20:03:52.023]:         message: An unexpected exception happened in thread main
[2017-12-14 20:03:52.023]:         
[2017-12-14 20:03:52.023]:         Exception:
[2017-12-14 20:03:52.023]:           java.lang.NoSuchMethodError:
[2017-12-14 20:03:52.023]:           com.apple.eawt.Application.removeAboutMenuItem()V
[2017-12-14 20:03:52.024]:         
[2017-12-14 20:03:52.024]:         You can get more details about the issue in the installer log file:
[2017-12-14 20:03:52.024]:          /Users/john/.application-installer/log/20171214200351.log
[2017-12-14 20:07:31.118]:         executing command: chmod ugo+x nbi-cleaner9315409774562967165.sh, in directory: /var/folders/1g/ntlc7xt92d59z_mkzycjxvq80000gn/T
[2017-12-14 20:07:31.145]:             [return]: 0
[2017-12-14 20:07:31.145]:         ... command execution finished
[2017-12-14 20:07:31.151]:         ... cleaning process has been started 

```

And building manually does not run the application from within netbeans at all.

Solution: delete java 9 and use 8 instead.

**Comment by JodderHL** [comment]
Netbeans is moving from Oracle to Apache hopefully they will update their tools for java 9 soon
